---
- hosts: ts
  tasks:
    - include_role:
        name: ts
      vars:
        icecast_address: live.linkmeup.ru
        icecast_password: "5BuziM39pTvaNj7okyAs"

- hosts: live
  become: "yes"
  tasks:
    - include_role:
        name: icecast2
      vars:
        source_password: "5BuziM39pTvaNj7okyAs"
...
