---
# handlers file for ts
- name: restart teamspeak
  become: "yes"
  service:
    name: teamspeak
    state: restarted
- name: reload systemd
  become: "yes"
  systemd:
    daemon_reload: "yes"
...
