name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install linter
        run: |
          sudo apt install python3-setuptools -y
          sudo pip3 install ansible-lint
          ansible-lint --version

      - name: Run linter
        run: ansible-lint playbook.yaml -v